[build]
builder = "NIXPACKS"
# Forzamos a Nixpacks a instalar solo dependencias de PHP e ignorar Node/NPM
buildCmds = ["composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"]

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
