[build]
builder = "NIXPACKS"
# Forzamos los paquetes nativos de PHP 8.4 que entienden perfectamente SHA2
nixPkgs = ["php84", "php84Packages.composer", "php84Packages.pdo_mysql"]
buildCmds = ["composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"]

[phases.predeploy]
cmds = [
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan migrate --force"
]
